#!/bin/sh

#Navigation aliases
alias pres="cd ~/Desktop/presentation/"
alias ircish="cd ~/.local/share/projects/old/IRCish"
alias skl="cd ~/Desktop/suckless/"
alias skewl="cd ~/Desktop/skewl/sem8"
alias scripts="cd ~/.local/bin"
alias bins="cd ~/.config/bin/"
alias binrs="cd ~/.config/bin/rst"
alias pr="cd ~/.local/share/projects"
alias arc="cd ~/Desktop/archive"
alias bk="cd ~/Desktop/backups/"
alias dt="cd ~/Desktop/backups/dotfiles"
alias ent="cd ~/Downloads/mediaserver/"
alias msk="cd ~/.local/share/myMusic/"
alias todo="vim ~/.local/store/todo/todo"
alias wrk="cd ~/projects/work"
alias work="wrk"
alias vimrcf="cd ~/.config/nvim/"
alias moz="cd /tmp/mozilla"

# alias wrkfl="cd ~/.local/share/projects/work/kvasir-ibmfl && cond && conda activate ibmfl"
# alias ibmfl="cd ~/.local/share/projects/work/kvasir-ibmfl/federated-learning-lib/editedWheel/ibmfl"

#Shortforms 
alias cl="clear"
alias cd..="cd .."
alias ..="cd .."
alias cpr="cp -r"
alias ex="extract"
alias rmf="rm -r"
alias sensor="watch -n 1 sensors"
alias ports="netstat -tulanp"
#Edit aliases
alias binds="vim ~/.config/sxhkd/sxhkdrc"
alias xrc="vim ~/.config/X11/xinitrc"
alias vima="vim /home/neil/.config/alacritty/alacritty.yml"

#Mispelling aliases
alias sl="ls"
alias l="ls"
alias claer="clear"
alias sulb="subl"

#Tmux aliases
alias tn="tmux -u  new"
alias ta="tmux -u  attach"
alias tl="tmux list-sessions"
alias muxt="vim /home/neil/.config/tmux/tmux.conf"

#Application Aliases
alias p="python3"
alias clip="xclip -sel clip"
alias clipp="xclip -selection clipboard -t image/png"
alias clipj="xclip -selection clipboard -t image/jpg"
alias build="sudo make clean install"
alias jup="jupyter notebook"
alias xfce="startxfce4"
alias urxvt='urxvt -bg "#1b1c1b" -fg "#ffffff" -fn "xft:Bitst'
alias musicDownload="youtube-dl -x"
alias ma="sshfs 192.168.0.118:/storage/emulated/0/  ~/Downloads/Android/ -p 2222" 
alias cat="bat --theme 'Monokai Extended'"
alias Cat="/usr/bin/cat"
alias emacs="echo 'Dont do this again please'"
alias jira="firefox https://team-1623308335956.atlassian.net/jira/software/projects/"
alias trello="firefox trello.com"
alias rstLearn="rustup doc --book"
alias topdf="soffice --headless --convert-to pdf"
alias img="sxiv"
alias tron="ssh sshtron.zachlatta.com"


# Command aliases
alias fixFn="sudo rtcwake -m mem -s 2"
alias tt="pdf /home/neil/Desktop/skewl/sem8/syllabus.pdf"
#Package manager aliases
alias install="sudo pacman -S"
alias remove="sudo pacman -Rns"
alias search="pacman -Ss"
alias update="paru -Pw ; paru -Syu"

#Default aliases
alias cp="cp -i"                          # confirm before overwriting something
alias df='df -h'                          # human-readable sizes
alias free='free -m'                      # show sizes in MB
alias np='nano -w PKGBUILD'
alias more='less'
alias grep="grep --color"
alias restart="sudo restart"
alias ll="ls -lha" #List everything in human readable form
alias ls="ls -hN --color=auto --group-directories-first" #Make ls human readable with color and directories first
alias lt="ls -hs1S"
alias size="du -ach | sort -h" #Gives size of eveything includeing folders
alias mkdir="mkdir -pv" #Make the necessary parent directories
alias startx="startx $XDG_CONFIG_HOME/X11/xinitrc"

# Show functions and aliases
alias aliases="grep --color=always -e '^$' -e "alias" '$XDG_CONFIG_HOME'/bash/aliases|less -R"
alias functions="grep --color=always -A 1 '(){' '$XDG_CONFIG_HOME'/bash/functions|less -R"

#For clearing home
alias wget='wget --hsts-file="$XDG_CACHE_HOME/wget-hsts"'



#Archive
#alias vhdl="wine /home/neil/.local/share/wineprefixes/default/drive_c/Modeltech_pe_edu_10.4a/win32pe_edu/modelsim.exe"

