
-- " Vim plug section ----------------- {{{
-- call plug#begin('~/.local/share/nvim/plugged')
-- " Declare the list of plugins.
-- Plug 'ericbn/vim-relativize'
-- Plug 'kshenoy/vim-signature'
-- Plug 'vim-airline/vim-airline'
-- Plug 'morhetz/gruvbox'
-- Plug 'lervag/vimtex'
-- Plug 'tpope/vim-fugitive'
-- Plug 'vim-utils/vim-man'
-- Plug 'mbbill/undotree'
-- Plug 'tpope/vim-commentary'
-- Plug 'junegunn/fzf', { 'do': { -> fzf#install() } }
-- Plug 'junegunn/fzf.vim'
-- Plug 'tpope/vim-vinegar'
-- Plug 'junegunn/goyo.vim'
-- Plug 'neoclide/coc.nvim', {'branch': 'release'}
-- " Plug 'nvim-lua/popup.nvim'
-- " Plug 'nvim-lua/plenary.nvim'
-- " Plug 'nvim-telescope/telescope.nvim'
-- "Plug 'ycm-core/YouCompleteMe' --> requires vim with python support
-- call plug#end()
-- " }}}

-- set background=dark
-- colorscheme gruvbox
