-- local cwd="/home/neil/.config/nvim/"
-- local pluginDirectory=cwd.."plugins/"
--t.testSome()
--
-- package.path=package.path..pluginDirectory
--
RequireReload"plugins.colorizer"
RequireReload"plugins.comment"
-- RequireReload"plugins.nvim-cmp"
-- RequireReload"plugins.feline"
-- RequireReload"plugins.luasnip"
-- RequireReload"plugins.obsidian"
RequireReload"plugins.snippets"
RequireReload"plugins.signs"
RequireReload"plugins.general_plugin_settings"
RequireReload"plugins.lsp"
RequireReload"plugins.nvim_devicons"
RequireReload"plugins.nvimtree"
RequireReload"plugins.telescope"
RequireReload"plugins.treesitter"
RequireReload"plugins.vimtex"
RequireReload"plugins.aerial"
RequireReload"plugins.liveserver"
-- RequireReload"plugins.refactor"
RequireReload"plugins.fterm"
RequireReload"plugins.comment"
RequireReload"plugins.wiki"
RequireReload"plugins.todo"
RequireReload"plugins.dap"
RequireReload"plugins.neogen"
RequireReload"plugins.indent"
RequireReload"plugins.harpoon"
RequireReload"plugins.worktree"
RequireReload"plugins.lualine"
