local map=vim.api.nvim_set_keymap
-- ('n',',r',':luafile dev/init.lua<cr>',{})

map("n","tn",":set invnumber<CR>",{})
map("n","tr",":RelativizeToggle<CR>",{})
map("n","So",":w<CR>:source $MYVIMRC<CR>",{})
map("n","Sp",":w<CR>:source $MYVIMRC<CR>:PlugInstall<CR>",{})
map("n","Sm",":setlocal foldmethod=marker<CR>",{})
map("n","Pi","So:PlugInstall<CR>",{})
map("n","<leader>c",":Telescope colorscheme<CR>",{})
map("n","<Esc>","<Esc><Esc>",{})
map("n","<leader>ev",":edit $MYVIMRC<CR>",{})
map("n","<leader>w",":w<CR>",{})
map("n","<leader>Q",":q!<CR>",{})
map("n","<leader>q",":q<CR>",{})
map("n","<leader>H",":noh<CR>",{})
map("n","<leader>R",":%s/",{})
map("n", "Q", "<Nop>",{}) 
map("n","<C-j>","<C-PageDown>",{})
map("n","<C-k>","<C-PageUp>",{})
map("n", "<C-Tab>",":tabn<CR>",{})

map("n", "<leader>gs",":G<CR><C-w>o",{})
map("n", "<leader>gc",":G commit<CR>",{})
map("n", "<leader>gf",":diffget //2<CR>",{})
map("n", "<leader>gj",":diffget //3<CR>",{})

map("n", "<leader>o",":Telescope find_files<CR>",{})
map("n", "<leader>O",":Telescope git_files<CR>",{})
map("n", "<leader>b",":Telescope buffers<CR>",{})
map("n", "<leader>t",":Telescope treesitter<CR>",{})
map("n", "<leader>s",":Telescope live_grep<CR>",{})
map("n", "<leader>f",":Telescope live_grep<CR>",{})

