#!/bin/bash
 # ~/.xinitrc
 #
 # Executed by startx (run your window manager from here)

 #Randomly set wallpaper
setWall -a
 #Screen compositor(enables smooth animation and window transparency
 picom &

#Simple X Hot Key Daemon(hotkey manager
sxhkd &

#Status bar script
#dwmbar &
dwmblocks &
#Notification daemon
dunst &

 #xset s 120 500
 #xss-lock slock

 userresources=$HOME/.Xresources
 usermodmap=$HOME/.Xmodmap
 sysresources=/etc/X11/xinit/.Xresources
 sysmodmap=/etc/X11/xinit/.Xmodmap
 # merge in defaults and keymaps
 if [ -f $sysresources ]; then
     xrdb -merge $sysresources
 fi

 if [ -f $sysmodmap ]; then
     xmodmap $sysmodmap
 fi

 if [ -f "$userresources" ]; then
     xrdb -merge "$userresources"
 fi

 if [ -f "$usermodmap" ]; then
     xmodmap "$usermodmap"
 fi

 # start some nice programs

 if [ -d /etc/X11/xinit/xinitrc.d ] ; then
     for f in /etc/X11/xinit/xinitrc.d/?*.sh ; do
         [ -x "$f" ] && . "$f"
     done
     unset f
 fi

 bash /home/neil/.config/bin/scrapers/runner.sh &
 #WM
exec dwm


 #Source .profile again
 #(incase of restart xserver while in-session)
 source ~/.profile
