#!/bin/sh
case $1 in
	--toggle-play) /home/neil/.config/bin/play -m -T;;
	--exit)/home/neil/.config/bin/play -m -e;;
	--prev)/home/neil/.config/bin/play -m -p;;
	--next)/home/neil/.config/bin/play -m -n;;
esac
