-- local opts={
--   '*'; -- Highlight all files, but customize some others.
--   '!vim'; -- Exclude vim from highlighting.
--   -- Exclusion Only makes sense if '*' is specified!
--   css = { rgb_fn = true; }; -- Enable parsing rgb(...) functions in css.
--   html = { names = false; mode = 'background'} -- Disable parsing "names" like Blue or Gray
-- }
--
-- return {
-- 	{
-- 		'norcalli/nvim-colorizer.lua',
-- 		opts={}
--
-- 	}
-- }
return {}
